kind: pipeline
name: deploy
type: docker

steps:

  - name: build-front
    image: docker:latest
    commands:
      - docker build -t rotour:client -f Dockerfile.prod .
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

  - name: deploy-front
    image: docker/compose
    commands:
      - docker-compose -f docker-compose.prod.yml up -d
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

  - name: discord notification
    image: appleboy/drone-discord
    when:
      status:
        - success
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        Une nouvelle version de https://rotour.dev est disponible !
        Info: {{build.message}}
        Version {{build.version}}
        owner : {{repo.owner}}
        name : {{repo.name}}
        status : {{build.status}}
        event : {{build.event}}
        number : {{build.number}}
        commit : {{build.commit}}
        message : {{build.message}}
        branch : {{build.branch}}
        tag : {{build.tag}}
        ref : {{build.ref}}
        author : {{build.author}}
        link : {{build.link}}
        started : {{build.started}}
        finished : {{build.finished}}


volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master