kind: pipeline
name: deploy
type: docker

steps:

  - name: build-front
    image: docker:latest
    commands:
      - docker build -t rotour:client -f Dockerfile.prod .
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

  - name: deploy-front
    image: docker/compose
    commands:
      - docker-compose -f docker-compose.prod.yml up -d
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

  - name: discord notification
    image: appleboy/drone-discord
    when:
      status:
        - failure
        - success
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: "
        Drone pipeline result for {{repo.name}}\n
        Duration: {{since build.started}}\n
        Commit: {{build.message}}\n
        {{#success build.status}}
          Build {{build.number}} ***succeeded***. Good job.
        {{else}}
          Build {{build.number}} ***failed***. Fix me please.
        {{/success}}
        "

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master