FROM node:22-alpine3.18 as builder

WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build


FROM node:22-alpine3.18
EXPOSE 3000
WORKDIR /app
COPY --from=builder /app/package.json .
COPY --from=builder /app/node_modules .
COPY --from=builder /app/build ./build/.
CMD ["node", "build/index.js"]