FROM node:16.18-alpine3.16 as builder

WORKDIR /app

COPY package.json .
RUN yarn --frozen-lockfile
COPY . .
RUN yarn build


FROM node:16.18-alpine3.16
EXPOSE 3000
WORKDIR /app
COPY --from=builder /app/package.json .
COPY --from=builder /app/node_modules .
COPY --from=builder /app/build ./build/.
CMD ["yarn", "start"]